# Generated by Django 2.0.3 on 2019-07-21 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('tag', models.CharField(choices=[('P_S1', 'Parrot Senario 1'), ('P_S2', 'Parrot Senario 2'), ('P_M', 'Parrot Movment'), ('P_A', 'Parrot Auto')], max_length=4)),
                ('arg', models.IntegerField(unique=True)),
                ('priority', models.IntegerField(default=10)),
                ('isVoice', models.BooleanField(default=False)),
                ('voiceFile', models.FileField(blank=True, upload_to='')),
                ('performTime', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnoseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField(default=False)),
                ('finish_time', models.BigIntegerField(default=0)),
                ('expertsystem_judgement', models.CharField(choices=[('اتیسم به احتمال قوی', 'اتیسم به احتمال قوی'), ('اتیسم به احتمال ضعیف', 'اتیسم به احتمال قوی'), ('عدم تشخیص اتیسم', 'اتیسم به احتمال قوی'), ('NA', 'NA')], default='NA', max_length=64)),
                ('paused', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_duration_minutes', models.SmallIntegerField()),
                ('wheel_duration_minutes', models.SmallIntegerField()),
                ('parrot_duration_minutes', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator])),
                ('birthYear', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=10)),
                ('medicalInfo', models.CharField(choices=[('ADHD', 'ADHD'), ('نرمال', 'نرمال'), ('اتیسم', 'اتیسم'), ('تعیین نشده', 'تعیین نشده')], max_length=10)),
                ('personID', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی عددی ۱۰ رقمی باید باشد', regex='^\\d{10}$')])),
                ('login_status', models.BooleanField(default=False)),
                ('last_activity', models.BigIntegerField(default=website.models.getTime)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField()),
                ('duration', models.IntegerField()),
                ('name', models.CharField(choices=[('NS', 'not started'), ('G', 'game'), ('W', 'Wheel'), ('P', 'parrot'), ('D', 'done')], default='NS', max_length=2)),
                ('expired', models.BooleanField(default=False)),
                ('auto_update', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToyCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField()),
                ('ac_x', models.BigIntegerField()),
                ('ac_y', models.BigIntegerField()),
                ('ac_z', models.BigIntegerField()),
                ('encode1', models.BigIntegerField()),
                ('encode2', models.BigIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.DiagnoseSession')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosesession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Patient'),
        ),
        migrations.AddField(
            model_name='diagnosesession',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Stage'),
        ),
    ]
