# Generated by Django 2.0.3 on 2018-12-08 13:52

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181010_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_activity',
            field=models.BigIntegerField(default=website.models.getTime),
        ),
    ]
