# defaults
DEFAULT_GAME_DURATION = 5
DEFAULT_WHEEL_DURATION = 5
DEFAULT_PARROT_DURATION = 5

NOT_STARTED_STAGE  = "NS"
GAME_STAGE = "G"
WHEEL_STAGE = "W"
PARROT_STAGE = "P"
DONE_STAGE = "D"
from website.ros import ROS
ros = ROS()